name: Build FFV1

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - uses: mymindstorm/setup-emsdk@v16
        with:
          version: 4.0.23
          actions-cache-folder: 'cache-emsdk'

      - uses: actions/cache@v3
        name: Cache dependencies
        with:
          key: cache-dependencies-${{ hashFiles('mk/*') }}
          path: build/*.tar*

      - run: make extract

      - run: make
      - name: Create FFV1 variant
        run: |
          cd configs
          node mkconfig.js ffv1-mkv '["encoder-ffv1", "format-matroska"]'
      
      - name: Show generated files
        run: |
          find configs -maxdepth 3 -type f | sort
      
      - name: Build FFV1 variant
        run: |
          make build-ffv1-mkv

      - name: Show output
        run: |
          ls -lh dist/*ffv1-mkv*

      - uses: actions/upload-artifact@v4
        with:
          name: libav-6.9.8.1-ffv1-mkv
          path: |
            dist/*ffv1-mkv*
